BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = no
NKRO_ENABLE = no

DEFAULT_FOLDER = crkbd/rev1

RGBLIGHT_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no

SPLIT_KEYBOARD = yes
LTO_ENABLE = yes
OLED_ENABLE = yes